### ISSUE TITLE
GET /articles/feed

### ISSUE THREAD

**Issue by nomisRev** [nomisRev/ktor-arrow-example#159]
In order to fully support articles we need to implement a _GET article feed_,
according to [following OpenAPI Spec](https://github.com/gothinkster/realworld/blob/main/api/openapi.yml).

```yaml
  /articles/feed:
    get:
      tags:
        - Articles
      summary: Get recent articles from users you follow
      description: Get most recent articles from users you follow. Use query parameters
        to limit. Auth is required
      operationId: GetArticlesFeed
      - name: offsetParam
         in: query
         name: offset
         required: false
         schema:
           type: integer
           minimum: 0
         description: The number of items to skip before starting to collect the result set.
       - name: limitParam
         in: query
         name: limit
         required: false
         schema:
           type: integer
           minimum: 1
           default: 20
         description: The numbers of items to return.
      responses:
        '200':
          $ref: '#/components/responses/MultipleArticlesResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '422':
          $ref: '#/components/responses/GenericError'
```

1. Add missing domain objects such as [`MultipleArticlesResponse`](https://github.com/gothinkster/realworld/blob/0ef2ba3996714c76e8f1a06cdd9895c4c3d8cd9a/api/openapi.yml#L604) domain object if it doesn't exist.
2. Create the missing SQLDelight queries, and implement `getFeed` in `ArticlePersistence`
3. Create `articles.kt` in `routes` if does not exist, or add `getFeed` operation there using `ArticlePersistence`.
4. Add test that verifies the behavior works

Please assign yourself to this ticket before starting, and if you run into any issues please raise a PR so I can provide help and support directly in the code.

Thank you in advance for your interest in the project! Happy hacktoberfest!

**Comment by Kaaveh** [comment]
Hey Simon
I never experienced server-side. I'd like to take a shot to contribute if you mind.

**Comment by Kaaveh** [comment]
Thanks! I'll work on it.

**Comment by Kaaveh** [comment]
Hey Simon,
Is it ok to `join` multiple tables (such as `articles`, `users`, and `following`)

![Screenshot 2023-10-19 at 12 17 14 PM](https://github.com/nomisRev/ktor-arrow-example/assets/39463024/97c15460-ee8a-4533-a42b-e337f7751751)

Or, I must aggregate data in the service layer?

![Screenshot 2023-10-19 at 12 18 31 PM](https://github.com/nomisRev/ktor-arrow-example/assets/39463024/a347a7ce-0c57-4fbe-b9b1-570fcf1d59b7)

**Comment by nomisRev** [comment]
Hey @Kaaveh,

Yes, I think that query that you shared is correct for article feed 👍 An inner join would be required here.
