### ISSUE TITLE
GET /articles/{slug}

### ISSUE THREAD

**Issue by nomisRev** [nomisRev/ktor-arrow-example#161]
In order to fully support tags we need to implement a GET article by slug,
according to [following OpenAPI Spec](https://github.com/gothinkster/realworld/blob/main/api/openapi.yml).

```yaml
  /articles/{slug}:
    get:
      tags:
        - Articles
      summary: Get an article
      description: Get an article. Auth not required
      operationId: GetArticle
      parameters:
        - name: slug
          in: path
          description: Slug of the article to get
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/SingleArticleResponse'
        '422':
          $ref: '#/components/responses/GenericError'
```

1. Add missing domain object [SingleArticleResponse](https://github.com/gothinkster/realworld/blob/0ef2ba3996714c76e8f1a06cdd9895c4c3d8cd9a/api/openapi.yml#L641C7-L641C7) if it doesn't exist.
2. Create `articles.kt` in routes if does not exist, and implement the route using `getArticleBySlug` using ArticlePersistence.
3. Add test that verifies the behavior works

Please assign yourself to this ticket before starting, and if you run into any issues please raise a PR so I can provide help and support directly in the code.

Thank you in advance for your interest in the project! Happy hacktoberfest!

**Comment by javimartinez** [comment]
Hi @nomisRev,  I want to learn Kotlin, Can I work on this ?

**Comment by nomisRev** [comment]
Hey @javimartinez,
Of course! If you have any questions, or doubts please raise a PR and we can discuss there ☺️
