### ISSUE TITLE
Use Ktor's Type Safe Routing (Resource DSL)

### ISSUE THREAD

**Issue by nomisRev** [nomisRev/ktor-arrow-example#170]
Update the routes to use Ktor's [type safe routing](https://ktor.io/docs/type-safe-routing.html#install_plugin).

**Comment by organize** [comment]
I can take this one!

**Comment by nomisRev** [comment]
@organize I would welcome `editorconfig` into the repo.
I've had issues with KtFmt and `editorconfig` since I didn't know exactly what the `editorconfig` needed to look like to match `KtFmt`, and it caused inconsistencies.
