### ISSUE TITLE
Fix the /api prefix according to the API Specification

### ISSUE THREAD

**Issue by nomisRev** [nomisRev/ktor-arrow-example#181]
code comments were erroneously prefixed with /api, though the API specification points to /api - but fixing this is for another PR

See #178 for more context

**Comment by nomisRev** [comment]
@organize

**Comment by organize** [comment]
Boo 👻 !

**Comment by organize** [comment]
Looking at the options, it's interesting how non-trivial something as trivial as this is with Resources:
* manually prefix all top-level routes with `/api`
  * a bit annoying to break out of the structuring provided by Resources API for this
* use Ktor's `rootPath` 
  * no clue if the Resources API respects this setting at all
  * would require some changes to SuspendApp to pass an environment (though this could be good in any case)
  * unintended side-effects as it's applied to all `routing { }` builders - optionally supplying some root with e.g. `routing<SomeResource> { }` might be a valid Ktor feature request
* use a top-level resource like `@Resource("/api") data object ApiRoot` and include it in every intermediate route
  * a lot of copy-pasting `(val parent: ApiRoot = ApiRoot)` everywhere, probably more serialization annotations to boot 😰 
  * it would be nice to at least use a sealed hierarchy here, but unfortunately the parent route needs to be in the constructor
* break resource hierarchy by skipping the parent reference and just wrap all relevant routes in `resource<ApiRoot> { }` - somehow™️ configure the test client to work with it
  
I think using `ApiRoot` as the parent in all of the constructors is the least evil option here even if it's slightly tedious. What do you think?
